Dw 2689 and dw2690
NHS-digital-website/hippo pull request #2023
Opened 2022-02-21 14:06 UTC by John-Milne

Use this branch for both DW-2689 and DW-2690

2022-02-24 09:43 UTC, GeoffreyHayward requested changes
This PR has noise that is unrelated to your change. Please rebase it and double-check that it only contains your expected changes and files.

2022-03-11 19:43 UTC, John-Milne commented
Updated grid breakout to use the same method as the video Jira DW-2692 so passed back for testing

2022-03-14 10:58 UTC, GeoffreyHayward requested changes
It's looking good. Please tidy the indentation first. Then it's good to go.

2022-03-14 10:58 UTC, GeoffreyHayward commented on repository-data/webfiles/src/main/resources/site/freemarker/nhsd-common/macro/heroes/base-hero.ftl
> +			            </#if>
Please tidy the formatting here.

2022-03-14 15:01 UTC, John-Milne commented on repository-data/webfiles/src/main/resources/site/freemarker/nhsd-common/macro/sections/imageModule.ftl
> +        </#if>
Formatting looks fine in IntelliJ and if you click on edit in here

2022-03-14 18:06 UTC, John-Milne commented on repository-data/webfiles/src/main/resources/site/freemarker/nhsd-common/macro/sections/imageModule.ftl
> +        </#if>
Inconsistencies show up in vi, so corrected using that

2022-03-28 07:30 UTC, merged